### ISSUE TITLE
Unable to use the SDK on iPhone5 and lower

### ISSUE THREAD

**Issue by siddheshcnaik** [OfficeDev/Office-365-SDK-for-iOS#79] opened 2015-08-19 17:39 UTC
Hi,

I am trying to make a calendar reservation using the iOS SDK. The login works fine. But on making call for making a calendar entry, I am getting following response.

Error in the Request Code=400 "The operation couldn’t be completed. (Error in the Request error 400.)" UserInfo=0x14d2a380 {error={
    code = RequestBodyRead;
    message = "Cannot read the value '0' as a quoted JSON string value.";
}}

Request Header:
{
    Authorization = "Bearer <TOKEN>";
    "Content-Type" = "application/json";
    "OData-MaxVersion" = "4.0";
    "OData-Version" = "4.0";
    "User-Agent" = "MSOutlookServicesClient/1.0 (lang=Objective-C; os=iPhone OS; os_version=8.3; arch=ARM; version=6)";
    "X-ClientService-ClientTag" = "Rooms/1.0 (lang=Objective-C; os=iPhone OS; os_version=8.3; arch=ARM; version=6)";
} 

Request Body:
{"Subject" : "Room Reservation","Body" : {"@odata.type" : "#Microsoft.OutlookServices.ItemBody","ContentType" : 0},"Importance" : 0,"HasAttachments" : 0,"Start" : "2015-08-19T17:40:00Z","StartTimeZone" : "Pacific Standard Time","End" : "2015-08-19T18:00:00Z","EndTimeZone" : "Pacific Standard Time","Reminder" : 0,"Location" : {"@odata.type" : "#Microsoft.OutlookServices.Location","DisplayName" : "ConfRm-MV-301 Qarth (4)"},"ShowAs" : 2,"IsAllDay" : 0,"IsCancelled" : 0,"IsOrganizer" : 0,"ResponseRequested" : 1,"Type" : 0,"Attendees" : [{"Type" : 0,"@odata.type" : "#Microsoft.OutlookServices.Attendee","EmailAddress" : {"@odata.type" : "#Microsoft.OutlookServices.EmailAddress","Address" : "ConfRm-MV-301-Qarth@miappdev.org"}}],"@odata.type" : "#Microsoft.OutlookServices.Event"}

NSHTTPURLResponse:
<NSHTTPURLResponse: 0x1653d4c0> { URL: https://outlook.office365.com/api/v1.0/Me/Events/ } { status code: 400, headers {
    "Cache-Control" = private;
    "Content-Type" = "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8";
    Date = "Wed, 19 Aug 2015 17:43:50 GMT";
    "OData-Version" = "4.0";
    Server = "Microsoft-IIS/8.0";
    "Set-Cookie" = "exchangecookie=4ac7ae4491604712b99c0f82cdb738a2; path=/";
    "Transfer-Encoding" = Identity;
    "X-AspNet-Version" = "4.0.30319";
    "X-BEServer" = BLUPR12MB0627;
    "X-BackEndHttpStatus" = 400;
    "X-CalculatedBETarget" = "BLUPR12MB0627.namprd12.prod.outlook.com";
    "X-DiagInfo" = BLUPR12MB0627;
    "X-FEServer" = CY1PR1201CA0017;
    "X-Powered-By" = "ASP.NET";
    "request-id" = "ad679a15-a808-4591-a850-fc3f2a7dbb90";
} }

Could any one please help?

Thanks,
Siddhesh

**Comment by anihojnadel** [comment] 2015-08-19 17:57
I've just tried to create an event with the SDK and it worked fine. Could you please send us the snippet you're using to reproduce the error? 

Thanks!

**Comment by siddheshcnaik** [comment] 2015-08-19 18:02
It fails only on iPhone 5/5c/4s and older iPad. I am not using any code snippet. The error only appears on the above mentioned devices. 

The code works fine on iPhone 5s/6/6Plus.
Following is the code used for creating the event and adding it:
MSOutlookServicesEvent *event = [[MSOutlookServicesEvent alloc] init];
    
    event.Subject = subject;
    [event setStart:start];
    [event setEnd:end];
    [event setRecurrence:MSOutlookServices_EventType_SingleInstance];
    MSOutlookServicesLocation *location = [[MSOutlookServicesLocation alloc] init];
    location.DisplayName = locationStr;
    [event setLocation: location];
    event.Body = [[MSOutlookServicesItemBody alloc] init];
    event.Body.Content = body;
    event.Body.ContentType = MSOutlookServices_BodyType_Text;
    event.responseRequested = YES;
    event.ShowAs = MSOutlookServices_FreeBusyStatus_Busy;
    
    NSString *timeZone = [[NSTimeZone localTimeZone] localizedName:NSTimeZoneNameStyleStandard locale:[NSLocale currentLocale]];
    event.StartTimeZone = timeZone;
    event.EndTimeZone = timeZone;
    
    NSMutableArray *toAttendees = [[NSMutableArray alloc] init];
    for (NSString *emailAddress in attendees) {
        MSOutlookServicesAttendee *attendee = [[MSOutlookServicesAttendee alloc] init];
        
        attendee.EmailAddress = [[MSOutlookServicesEmailAddress alloc] init];
        attendee.EmailAddress.Address = emailAddress;
        attendee.type = MSOutlookServices_AttendeeType_Required;
        
        [toAttendees addObject:attendee];
    }
    
    event.Attendees = [toAttendees copy];

Office365ClientFetcher *clientFetcher = [[Office365ClientFetcher alloc] init];
    
    [clientFetcher fetchOutlookClient:^(MSOutlookServicesClient *client, AuthenticationStatus status) {
        MSOutlookServicesUserFetcher *userFetcher = [client getMe];
        MSOutlookServicesEventCollectionFetcher *eventCollectionFetcher = [userFetcher getEvents];
        
        NSURLSessionTask *task = [eventCollectionFetcher addEvent:event
                                                         callback:^(MSOutlookServicesEvent *addedEvent, MSODataException *error) {
                                                             completion(addedEvent, error);
                                                         }];
        
        [task resume];
    }];

**Comment by anihojnadel** [comment] 2015-08-19 18:44
I tried using your code but it doesn't compile with current version of the sdk.

Which SDK version are you using?

**Comment by siddheshcnaik** [comment] 2015-08-19 18:46
We are using V 0.9.0

**Comment by anihojnadel** [comment] 2015-08-19 18:50
Could you try updating to 0.11.0 ? It seems the endpoint changed since that version and the request the SDK is generating is invalid.

All our SDKs are generated using the endpoint's metadata, if the endpoint changes for some reason we regenerate the SDK with the new features. It could happen that a previous version of the SDK doesn't work anymore since the endpoint expects something different.

Please, try with the new version and let us know.

**Comment by siddheshcnaik** [comment] 2015-08-19 21:55
I was able to fix the issue.

Issue exist because of Property.m code.

-(bool)isBoolean{
    return [self.Type isEqualToString:@"TB"]; // On ARMv6/7 Boolean is "Tc"
}

-(bool)isEnum{
    return [self.Type isEqualToString:@"Tq"]; //On ARMv6/7 Boolean is "Ti"
}
This causes the JSON to be miss formed. This is issue is also present in the latest 0.11.0 SDK.

**Comment by anihojnadel** [comment] 2015-08-20 13:38
Thanks a lot for your help! We're working on some SDK updates and we'll include the fix in a future release.

In the meantime, please use your fix. We'll let you know once it's ready.

**Comment by anihojnadel** [comment] 2015-11-19 14:15
This should be fixed in the new version of the SDK.

https://github.com/OfficeDev/Outlook-SDK-iOS

**Closed by anihojnadel** 2015-11-19 14:15 UTC
Labels: bug

**Comment by rumit123** [comment] 2015-11-30 12:52
Hi,

I am trying to add make calendar events in my iphone, but i can't able to add it.
Can you please help out to solve this issue?

 Following is the code used for creating the event and adding it:

    NSDateFormatter *formatter;
    NSString        *dateString;
    formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:@"yyyy-dd-MM 'at' HH:mm"];
    NSDate *start = _dictionaryData[@"date"];
    dateString = [formatter stringFromDate:start];
    // Populate the event details
    NSString *toEmailAddress = [[NSUserDefaults standardUserDefaults] objectForKey:@"LogInUser"];
    NSString *subject = [NSString stringWithFormat:@"Testing event created on %@", dateString];
    NSString *body = @"Congratulations, you created  this event from the Roombit app! for testing ";
    double interval=0;
    if ([_dictionaryData[@"time"] integerValue]==1) {
        interval=15*60;
    }else if ([_dictionaryData[@"time"] integerValue]==2) {
        interval=30*60;
    }else if ([_dictionaryData[@"time"] integerValue]==3) {
        interval=45*60;
    }else if ([_dictionaryData[@"time"] integerValue]==4) {
        interval=60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==5) {
        interval=2*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==6) {
        interval=3*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==7) {
        interval=4*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==8) {
        interval=5*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==9) {
        interval=6*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==10) {
        interval=7*60*60;
    }else if ([_dictionaryData[@"time"] integerValue]==11) {
        interval=8*60*60;
    }
    NSDate *end = [start dateByAddingTimeInterval:interval];
    
    MSOutlookEvent *eventToCreate = [snippetLibrary outlookEventWithProperties:@[toEmailAddress]
                                                                       subject:subject
                                                                          body:body
                                                                         start:start
                                                                           end: end
                                     ];
    MSOutlookLocation *objectLocation=[[MSOutlookLocation alloc] init];
    objectLocation.DisplayName=SharedCommon.arrayRoomList[indexRoom][@"address"];
    [eventToCreate setLocation:objectLocation];
        NSLog(@"start:%@",start);
    NSLog(@"end:%@",end);
    [snippetLibrary createCalendarEvent:eventToCreate
                             completion:^(MSOutlookEvent *addedEvent,  NSError *error) {
                                 dispatch_async(dispatch_get_main_queue(), ^{
                                 [SharedCommon showHideLoadingView:NO withView:self.view];
                                 });

                                 if (error == nil) {
                                     dispatch_async(dispatch_get_main_queue(), ^{
                                         NSMutableDictionary *dictionaryData=[NSMutableDictionary dictionary];
                                         [dictionaryData setObject:start forKey:@"start_date"];
                                         [dictionaryData setObject:end forKey:@"end_date"];
                                         [dictionaryData setObject:[NSMutableDictionary dictionaryWithDictionary:SharedCommon.arrayRoomList[indexRoom]] forKey:@"beacon"];
                                         [self performSegueWithIdentifier:@"SegueConfirmedRoom" sender:dictionaryData];
                                         dictionaryData=nil;
                                     });
                                 }
                             }];


I am getting following error.

error =     {
        code = RequestBodyRead;
        message = "Cannot convert the literal '0' to the expected type 'Edm.Boolean'.";
    };


Thanks in advance.
